### ISSUE TITLE
gatsby-source-google-reviews-en Error fetching results from ScaleSerp API: Error: Request failed with status code 400 

### ISSUE THREAD

**Issue by udemezue01** [KennyHammerlund/gatsby-source-google-reviews-en#1]
I installed the latest version of gatsby-source-google-reviews-en to retrieve the Google review of a client, however, I tried it on the first day and it worked, on return to the second day to test it again, I get an empty array.

The following errors.

```

"gatsby-source-google-reviews-en" threw an error while running the sourceNodes lifecycle:

Error fetching results from ScaleSerp API: Error: Request failed with status code 400

  37 |     })
  38 |     .catch((error) => {
> 39 |       throw new Error(`Error fetching results from ScaleSerp API: ${error}`);
     |             ^
  40 |     });
  41 |
  42 |   if (!response || !response.data)

File: node_modules\gatsby-source-google-reviews-en\gatsby-node.js:39:13



  Error: Error fetching results from ScaleSerp API: Error: Request failed with status code 400

  - gatsby-node.js:39 
    [raganortho]/[gatsby-source-google-reviews-en]/gatsby-node.js:39:13

  - task_queues.js:95 processTicksAndRejections
    internal/process/task_queues.js:95:5

  - gatsby-node.js:34 Object.exports.sourceNodes
    [raganortho]/[gatsby-source-google-reviews-en]/gatsby-node.js:34:20

  - api-runner-node.js:434 runAPI
    [raganortho]/[gatsby]/src/utils/api-runner-node.js:434:16



```
For more clarification, here is how I set my gatsby-source-google-reviews-en in my source code.
```
{
      resolve: `gatsby-source-google-reviews-en`,
      options: {
        placeId:`ChIJDdsPF6whTIYR3omS_FD6Iyw`,

        apiKey:`F66B09A0B8854F1DB9095E91D1438B17`,

      },
    },

```

### Reproduction Link

https://github.com/udemezue01/KL-Issues

### Steps to Reproduce

1. Clone reproduction link

2. Run "gatsby develop"

3. Launch http://localhost:8000/___graphql

4. Run the query below.
```
query MyQuery {
  allGoogleReview {
    nodes {
      body
      children {
        id
      }
    }
  }
}
```

**Comment by KennyHammerlund** [comment]
Is your key valid in scaleserp? If it’s getting a 400 from them it’s something to do with their service and not the plug-in. 400,  maybe you are over your limit for queries? 

I have been meaning to remove that portion and run it directly off google keys but I have not had the time.

**Comment by udemezue01** [comment]
I created a different scaleserp account, but I get the same errors, any help?

**Comment by udemezue01** [comment]
No solution yet sir

**Comment by udemezue01** [comment]
Thanks, I solved it already and the issue was with the Google placed API, I obtained another key.
